#! /usr/bin/python3

import os
from typing import List

from modules import cf_args

from modules.cf_checker import *
from modules.cf_output import *
from modules.output import *
from modules.checker import *

import json

if __name__ == "__main__":
    
    args = cf_args.load_args()

    progress_printer = get_progress_printer(args=args)
    error_printer = get_error_printer(args=args)

    progress_printer("Path : " + args.path)
    if args.optionsFile != None:
        progress_printer("Using Options File from : " + args.path)
    if len(args.includePaths) > 0:
        progress_printer("Include Paths : " + " : ".join(args.includePaths))
    if args.outputFile is not None:
        progress_printer("Output File : " + os.path.realpath(args.outputFile.name))
        progress_printer("Output Format : " + args.formatClass)
    else:
        progress_printer("Output File : stdout")
        progress_printer("Output Format : JSON")

    progress_printer("\nRunning CodeFree Analysis...")

    try:
        CheckingModule.run_checks(args=args)
    except KeyboardInterrupt:
        print("Recieved Interrupt, Partials Results will be written to Output.")

    CheckerStats.calculateStats(args=args)
    CheckerStats.printStats(args=args)

    FormattingModule.generate_output(args=args)
    
    progress_printer("Done.")