"""Added User Sessions table

Revision ID: 6168d4ea2538
Revises: 9a917117d777
Create Date: 2025-01-08 22:55:14.189784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6168d4ea2538'
down_revision: Union[str, None] = '9a917117d777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersession',
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=False),
    sa.Column('session_ip', sa.String(length=15), nullable=False),
    sa.Column('session_user_agent', sa.String(length=255), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_name', 'session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersession')
    # ### end Alembic commands ###
