"""Added_Unique_To_SessionID

Revision ID: 7adb9eed06f6
Revises: c49aa3d94861
Create Date: 2025-01-10 19:29:54.641992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adb9eed06f6'
down_revision: Union[str, None] = 'c49aa3d94861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersession', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_session_id', ['session_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersession', schema=None) as batch_op:
        batch_op.drop_constraint('unique_session_id', type_='unique')

    # ### end Alembic commands ###
