"""Increased cf_code_quality_score Precision

Revision ID: c49aa3d94861
Revises: c813a0d8a3a8
Create Date: 2025-01-09 11:14:27.854139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49aa3d94861'
down_revision: Union[str, None] = 'c813a0d8a3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
