"""Added cf_code_quality_score to report

Revision ID: c813a0d8a3a8
Revises: 6168d4ea2538
Create Date: 2025-01-09 11:11:15.767388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c813a0d8a3a8'
down_revision: Union[str, None] = '6168d4ea2538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('cf_code_quality_score', sa.Float(precision=2), server_default=sa.text('(0.0)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'cf_code_quality_score')
    # ### end Alembic commands ###
